### ISSUE TITLE
Ombrejat de la zona no RMB

### ISSUE THREAD

**Issue by jagorce** [letbcn/let-viewer#1]
Hola!! 
No sé que passa o ha canviat, a la versió antiga del script al Atlantis tot el territori que quedava fora de la RMB apareixia ombrejat per destacar la informació de dins del nostre àmbit d'estudi.
Ara això no succeeix, jo no he canviat res d'aquesta part. 
Potser té relació amb les capes de la màscara RMB?

Gràcies

**Comment by Iferrero** [comment]
Hola,
El feature class que s'utilitza ara és https://openlab.uab.es:6443/arcgis/rest/services/limits_administratius/municipis/FeatureServer/0
Abans el feature server era https://atlantis.uab.cat:6443/arcgis/rest/services/limits_administratius/limits_administratius/FeatureServer/3
És sobre aquests feature que es fa el filtre i es pinta. A partir de la linia 52 de map.js

**Comment by jagorce** [comment]
Solucionat!! Gràcies.
Ara penjo el nou codi.
